#import "@preview/basic-resume:0.2.4": *

#let name = "Attila Jamilov"
#let location = "Bellevue, WA"
#let email = "attilajam"
#let github = "github.com/attilajam"
#let linkedin = "linkedin.com/in/attila-jamilov"
#let phone = "+1 (425) 429-8450"
#let personal-site = "stuxf.dev"

#show: resume.with(
  author: name,
  location: location,
  email: email,
  github: github,
  linkedin: linkedin,
  phone: phone,
  // personal-site: personal-site,
  accent-color: "#26428b",
  font: "New Computer Modern",
  paper: "us-letter",
  author-position: left,
  personal-info-position: left,
)

== Education

#edu(
  institution: "University of Washington",
  location: "Seattle, WA, Sep. 2023 - Mar. 2026",
  // dates: dates-helper(start-date: "Aug 2023", end-date: "May 2027"),
  degree: "Bachelor's of Science, ACMS: Discrete Math and Algorithms, Computational Finance and Risk Management",
)
- Competitive Programming Club, 
- *Relevant Coursework*: Data Structures, Algorithms, Financial Markets, Stochastic Calculus, Combinatorics I and II, C++ programming, Linear Optimization, Discrete Optimization, Machine Learning with Application to Finance, Probability, Numerical Analysis I and II, Quantitative Statistics for Data Science, Data Visualization. 
#edu(
  institution: "Bellevue College",
  location: "Bellevue, WA, Sep. 2021 - June. 2023",
  degree: "Associate's of Arts and Sciences, Running Start Program",
)
- *Relevant Coursework*: Calculus I, II, III, and IV, Computer Science II.
== Work Experience

#work(
  title: "Research Assistant",
  location: "Seattle, WA",
  company: "Math AI Lab, University of Washington",
  dates: dates-helper(start-date: "Jan. 2025", end-date: "Present"),
)
- Built the Machine-to-Machine interacting layer, to allow Python to interface with the Lean4 theorem proving language, allowing Python to test possible proofs from LLMs or PyTorch models into Lean. 
- Implemented A-Star Search to traverse the possible proof states to complete the proof. Developed heuristics to guide the search, making the traversal through the tree quicker.
- Incorporated the LeanDojo tactic generation model, evaluated the search on minif2f, scored 29% on this olympiad-level benchmark. 
- Created a framework to quickly test other models, LLMs, etc. 
- Contributed to #link("https://github.com/stanford-centaur/PyPantograph", "PyPantograph"), the Python package that interacts with Lean. My contribution made it possible to build the package on Windows.
#work(
  title: "AI Coding Analyst",
  company: "Scale AI",
  dates: dates-helper(start-date: "May. 2024", end-date: "Jan. 2025")
)
- Improved LLM models by prompt engineering the model to breakdown and create improper answers to the prompt, revised the code that was generated by the model to correctly achieve the prompt, which overall improved various LLMs. 
- Responsible for other contributors, reviewed their work to ensure that the code is up to the standard of the client, as well as on-time. 
- Supported contributors by providing suggestions and feedback on their work, improving the quality of code submitted.
== Projects
#project(
  dates: 2024,
  name: "Auction API Analyzer",
)
- Developed a Go backend that requests data from the Hypixel Skyblock API, gathering all 60000 auctions listed currently, and then calls the Coflnet API and performs a union on the two sets of data. Made use of Go routines to sort through the data quicker.
- Created a front-end using Go templates, allowing the user to search through all of the auctions listed currently. Added filters, such as minimum price, minimum profit, allowing the user to quickly find items that were listed for too little on the auction.

== Skills
*Languages*: Python (2 years), Go (1 year), C/C++ (1 year), Rust (1 year), HTML, CSS, JS, Ocaml, Ruby, R, Assembly \
*Frameworks*: Flask, Go templates, Fast API \
*Developer Tools*: Git, Google Cloud Platform, AWS, VS code, Visual Studio, Neovim \
*Documents*: Typst, Latex \ 
*Libraries*: NumPy, pandas, requests, Selenium, BeautifulSoup, PyTorch, Asyncio, tensorflow, matplotlib, scikitlearn \
*Interests*: Rock climbing, Books, Manga/Manhua, Linux (Arch, Hyprland), optimizing productivity. 
